import {PlaceEvidence} from './PlaceEvidence';
import {terrainReview} from '../data/real-campus';
import {useState, useId, useEffect} from 'react';
import {Search, SlidersHorizontal, MapPin, X, ChevronLeft, ChevronRight, RotateCcw, Shuffle, Share2, Camera, Compass, Layers, Play, Pause, BookOpen, Route, Sun, Moon, Flower2, TreeDeciduous, Leaf, Snowflake, Info, Maximize2, Eye, Building2, ArrowUpRight, PanelLeftClose, PanelRightClose} from 'lucide-react';
import type {SceneState,Landmark,TourRoute,Era,ViewMode} from '../types';
import {mapMeta} from '../data/campus';
type Props={state:SceneState;landmarks:Landmark[];tours:TourRoute[];eras:{id:Era;title:string;period:string;year:number;description:string}[];selected:Landmark|undefined;onChange:(p:Partial<SceneState>)=>void;onSelect:(id:string)=>void;onView:(view:ViewMode)=>void;onShare:()=>void;onCapture:()=>void;onReset:()=>void;onRegenerate:()=>void;onTour:(id:string)=>void;onTourToggle:()=>void;onTourStep:(d:1|-1)=>void;onTourStop:()=>void;tour:{routeId:string;index:number;playing:boolean}|null;notice:string;ready:boolean;stats:{fps:number;calls:number;triangles:number}|null};
const categories=[['all','全部'],['scenic','校园风物'],['dining','食堂'],['teaching','教学楼'],['sports','运动场馆'],['department','能动与法学'],['life','校园生活']];
const seasons=[{id:'spring',title:'春',icon:Flower2},{id:'summer',title:'夏',icon:TreeDeciduous},{id:'autumn',title:'秋',icon:Leaf},{id:'winter',title:'冬',icon:Snowflake}] as const;
const timeText=(time:number)=>`${String(Math.floor(time)).padStart(2,'0')}:${String(Math.round((time%1)*60)).padStart(2,'0')}`;
function Slider({label,value,min=0,max=100,step=1,onChange,display,icon}:{label:string;value:number;min?:number;max?:number;step?:number;onChange:(v:number)=>void;display?:string;icon?:React.ReactNode}){const id=useId();return <div className="slider-field"><div className="field-heading"><label htmlFor={id}>{icon}{label}</label><output htmlFor={id}>{display??`${Math.round(value)}%`}</output></div><input id={id} aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))} style={{'--progress':`${(value-min)/(max-min)*100}%`} as React.CSSProperties}/></div>;}
export function Editor(p:Props){
 const [leftOpen,setLeftOpen]=useState(()=>window.innerWidth>760),[rightOpen,setRightOpen]=useState(()=>window.innerWidth>760),[tab,setTab]=useState<'places'|'tours'>('places'),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[info,setInfo]=useState(false);
 const mobile=()=>window.innerWidth<=760;
 useEffect(()=>{if(p.selected&&!p.tour){setLeftOpen(true);if(window.innerWidth<=760)setRightOpen(false);}},[p.selected?.id,p.tour?.routeId]);
 const openLeft=()=>{setLeftOpen(v=>!v);if(mobile())setRightOpen(false);},openRight=()=>{setRightOpen(v=>!v);if(mobile())setLeftOpen(false);};
 const items=p.landmarks.filter(l=>(category==='all'||l.focus?.includes(category))&&`${l.name}${l.subtitle}${l.aliases?.join(' ')}`.includes(query.trim()));
 const currentEra=p.eras.find(e=>e.id===p.state.era)!;
 const currentRoute=p.tours.find(r=>r.id===p.tour?.routeId);
 const select=(id:string)=>{p.onSelect(id);setLeftOpen(true);if(mobile())setRightOpen(false);};
 return <div className="editor-layer">
  <header className="topbar"><div className="brand"><div className="brand-seal">清</div><div><h1>清华园境<span>3D 校园漫游</span></h1><p>一座校园，百年光阴。</p></div></div><div className="header-actions"><span className="site-chip"><span/>海淀 · 清华园</span><button className="icon-button" title="操作与资料来源" aria-label="操作与资料来源" onClick={()=>setInfo(true)}><Info size={18}/></button><button className="header-button" aria-label="分享此刻" onClick={p.onShare}><Share2 size={16}/><span>分享此刻</span></button><button className="header-button primary" aria-label="四季明信片" onClick={p.onCapture} disabled={!p.ready}><Camera size={16}/><span>四季明信片</span></button></div></header>
  {!leftOpen&&<button className="panel-launch left" onClick={openLeft}><MapPin size={17}/><span>建筑与导览</span></button>}
  {!rightOpen&&<button className="panel-launch right" onClick={openRight}><SlidersHorizontal size={17}/><span>景观编辑</span></button>}
  <aside className={`panel places-panel ${leftOpen?'open':''}`} aria-label="建筑与导览">
   <div className="panel-top"><span className="eyebrow">发现清华园</span><button className="icon-button" aria-label="收起建筑面板" onClick={()=>setLeftOpen(false)}><PanelLeftClose size={17}/></button></div>
   <div className="panel-tabs"><button className={tab==='places'?'active':''} onClick={()=>{setTab('places');p.onChange({selected:null});}}><Building2 size={16}/>校园建筑</button><button className={tab==='tours'?'active':''} onClick={()=>{setTab('tours');p.onChange({selected:null});}}><Route size={16}/>云导览</button></div>
   <div className="panel-scroll">
    {p.selected?<article className="place-detail"><button className="back-link" onClick={()=>p.onChange({selected:null})}><ChevronLeft size={15}/>返回{tab==='places'?'建筑列表':'导览路线'}</button><PlaceEvidence key={p.selected.id} place={p.selected}/><p className="eyebrow">{categories.find(c=>c[0]===p.selected?.focus?.[0])?.[1]}</p><h2>{p.selected.name}</h2><p className="detail-subtitle">{p.selected.subtitle}</p><div className="style-label"><Layers size={14}/>{p.selected.style}</div><p className="detail-body">{p.selected.description}</p><ul className="fact-list">{p.selected.facts.map(f=><li key={f}>{f}</li>)}</ul><button className="full-button" onClick={()=>p.onView('ground')}><Eye size={16}/>从地面看建筑</button><div className="source-list"><span>进一步阅读</span>{p.selected.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title}<ArrowUpRight size={13}/></a>)}</div></article>:tab==='places'?<><div className="search-box"><Search size={16}/><input aria-label="搜索校园建筑" placeholder="寻找一座建筑…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清空搜索" onClick={()=>setQuery('')}><X size={14}/></button>}</div><div className="category-chips">{categories.map(([id,title])=><button key={id} className={category===id?'active':''} onClick={()=>setCategory(id)}>{title}</button>)}</div><div className="list-meta"><span>{query?`找到 ${items.length} 处地点`:'校园建筑与风景'}</span><span>{items.length} 处</span></div><div className="place-list">{items.map(l=><button className={`place-item ${l.category}`} key={l.id} onClick={()=>select(l.id)}><span className="place-icon">{['water','garden'].includes(l.model)?<TreeDeciduous size={20}/>:l.category==='department'?<BookOpen size={20}/>:<Building2 size={20}/>}</span><span className="place-item-text"><strong>{l.name}</strong><small>{l.subtitle}</small></span><ChevronRight size={14}/></button>)}{items.length===0&&<p className="empty">还没有找到这座建筑，试试“能动”或“法学”。</p>}</div></>:<div className="tour-list"><p className="tour-intro">沿一条路线，听建筑讲述清华。<br/>拖动镜头，随时停下来看看。</p>{p.tours.map((r,i)=><article className="tour-card" key={r.id}><div className="tour-number" style={{color:r.color}}>0{i+1}<Route size={22}/></div><h3>{r.name}</h3><p>{r.subtitle}</p><div className="tour-card-bottom"><span>{r.stops.length} 站 · 约 {Math.ceil(r.stops.length*9.5)} 秒</span><button onClick={()=>{p.onTour(r.id);if(mobile())setLeftOpen(false);}} aria-label={`开始${r.name}导览`}><Play size={14} fill="currentColor"/>出发</button></div></article>)}</div>}
   </div><div className="panel-bottom"><MapPin size={13}/><span>校园示意沙盘 · 点选建筑了解更多</span></div>
  </aside>
  <aside className={`panel settings-panel ${rightOpen?'open':''}`} aria-label="景观编辑">
   <div className="panel-top"><span className="eyebrow">景观工作室</span><button className="icon-button" aria-label="收起景观面板" onClick={()=>setRightOpen(false)}><PanelRightClose size={17}/></button></div><div className="settings-title"><h2>让清华园，随心而变</h2><p>四季、花木与一日的光影</p></div>
   <div className="panel-scroll settings-scroll"><section className="control-section"><h3><Sun size={16}/>季节与光影<span>01</span></h3><div className="season-buttons">{seasons.map(s=><button key={s.id} aria-label={`${s.title}季`} className={p.state.season===s.id?'active':''} onClick={()=>p.onChange({season:s.id})}><s.icon size={18}/>{s.title}</button>)}</div><Slider label="一天中的时刻" value={p.state.time} min={0} max={24} step={.25} display={timeText(p.state.time)} onChange={time=>p.onChange({time})}/><div className="range-ends"><span>午夜</span><span>正午</span><span>午夜</span></div><Slider label="曝光" value={p.state.exposure} min={.6} max={1.6} step={.05} display={`${p.state.exposure.toFixed(2)} ×`} onChange={exposure=>p.onChange({exposure})}/></section>
   <section className="control-section"><h3><Flower2 size={16}/>校园花木<span>02</span></h3><Slider label="植被丰茂度" value={p.state.trees} max={150} onChange={trees=>p.onChange({trees})}/><Slider label="丁香花量" value={p.state.lilac} icon={<span className="flower-dot lilac"/>} onChange={lilac=>p.onChange({lilac})}/><Slider label="紫荆花量" value={p.state.cercis} icon={<span className="flower-dot cercis"/>} onChange={cercis=>p.onChange({cercis})}/><p className="control-hint">春日花开；夏、秋、冬随季节收敛。<br/>花木为自由布景，建筑位置保持不变。</p></section>
   <section className="control-section"><h3><TreeDeciduous size={16}/>校园日常<span>03</span></h3><Slider label="人流与自行车" value={p.state.activity} onChange={activity=>p.onChange({activity})}/><div className="field-heading"><label htmlFor="quality">画面质量</label><select id="quality" aria-label="画面质量" value={p.state.quality} onChange={e=>p.onChange({quality:e.target.value as SceneState['quality']})}><option value="auto">自动适配</option><option value="high">精细画面</option><option value="low">轻量流畅</option></select></div><label className="toggle-row"><span>显示建筑名称</span><input aria-label="显示建筑名称" type="checkbox" checked={p.state.labels} onChange={e=>p.onChange({labels:e.target.checked})}/><span className="toggle-track"/></label></section>
   <section className="control-section view-section"><h3><Compass size={16}/>观察清华园<span>04</span></h3><div className="view-buttons">{([{id:'isometric',title:'沙盘',icon:Layers},{id:'overhead',title:'俯瞰',icon:Maximize2},{id:'ground',title:'地面',icon:Eye},{id:'cinematic',title:'环绕',icon:Camera}] as const).map(v=><button key={v.id} aria-label={`${v.title}视角`} className={p.state.view===v.id?'active':''} onClick={()=>p.onView(v.id)}><v.icon size={17}/>{v.title}</button>)}</div></section>
   </div><div className="settings-footer"><button onClick={p.onReset}><RotateCcw size={14}/>重置</button><button onClick={p.onRegenerate}><Shuffle size={14}/>重新布景</button></div>
  </aside>
  {p.tour&&currentRoute&&<div className="tour-player" aria-label="导览播放器"><div className="tour-player-heading"><Route size={17}/><div><strong>{currentRoute.name}</strong><span>{p.tour.index+1} / {currentRoute.stops.length} · {p.selected?.name}</span></div><button className="icon-button" aria-label="退出导览" onClick={p.onTourStop}><X size={16}/></button></div><div className="tour-progress">{currentRoute.stops.map((id,i)=><span key={id} className={i<=p.tour!.index?'done':''}/>)}</div><div className="tour-player-controls"><button aria-label="上一站" onClick={()=>p.onTourStep(-1)}><ChevronLeft size={18}/></button><button className="play-control" aria-label={p.tour.playing?'暂停导览':'继续导览'} onClick={p.onTourToggle}>{p.tour.playing?<Pause size={16}/>:<Play size={16}/>}<span>{p.tour.playing?'暂停':'继续'}</span></button><button aria-label="下一站" onClick={()=>p.onTourStep(1)}><ChevronRight size={18}/></button></div></div>}
  <div className="scene-caption"><Compass size={19}/><div><strong>{p.selected?.name??'清华大学 · 海淀校区'}</strong><span>{p.state.era==='today'?`${seasons.find(s=>s.id===p.state.season)?.title}日 ${timeText(p.state.time)}`:currentEra.title} · 校园示意沙盘</span></div><button aria-label="回到全校沙盘" title="回到全校沙盘" onClick={()=>{p.onChange({selected:null});p.onReset();}}><Maximize2 size={16}/></button></div>
  <footer className="timeline calibration-footer"><div className="timeline-heading"><MapPin size={18}/><div><strong>当代清华园</strong><span>官方地图对照版 · v1.1</span></div></div><div className="calibration-summary"><strong>{p.landmarks.length} 处地点</strong><span>轮廓与来源可查 · 高程待核实</span></div><a href={mapMeta.source} target="_blank" rel="noreferrer">对照官方地图<ArrowUpRight size={14}/></a><button className="timeline-info" aria-label="地图与核实说明" onClick={()=>setInfo(true)}><Info size={17}/></button></footer>
  <div className="mobile-dock"><button className={leftOpen?'active':''} onClick={openLeft}><MapPin size={18}/>建筑与导览</button><button className={rightOpen?'active':''} onClick={openRight}><SlidersHorizontal size={18}/>景观编辑</button></div>
  {p.notice&&<div className="toast" role="status">{p.notice}</div>}
  {!p.ready&&<div className="loading-screen"><div className="loading-seal">清</div><h2>走进清华园</h2><p>正在铺开校园与四季风景…</p><span className="loading-line"/></div>}
  {info&&<div className="modal-overlay" onClick={()=>setInfo(false)}><section className="info-modal" role="dialog" aria-modal="true" aria-label="操作与资料来源" onClick={e=>e.stopPropagation()}><button className="icon-button modal-close" aria-label="关闭说明" onClick={()=>setInfo(false)}><X size={19}/></button><p className="eyebrow">清华园境</p><h2>在校园里，慢慢走。</h2><p>拖动旋转，滚轮缩放，右键平移。手机单指旋转，双指缩放与平移。点选建筑查看介绍；自动导览中拖动镜头可暂停。</p><h3>{currentEra.title} <small>{currentEra.period}</small></h3><p>{currentEra.description}</p><h3>关于这座沙盘</h3><p>{mapMeta.precision} 包括附中本部、附小清华园校区和校内家属区。</p><p>清华标准紫为 #660874，校花为紫荆及紫、白丁香。建筑的现状用途与历史沿革分别介绍。</p><div className="modal-sources"><a href="?mode=2d">以二维概览查看校园<ArrowUpRight size={14}/></a><a href={mapMeta.source} target="_blank" rel="noreferrer">官方校园地图 · {mapMeta.updated}<ArrowUpRight size={14}/></a><a href="https://xsg.tsinghua.edu.cn/info/1003/1156.htm" target="_blank" rel="noreferrer">校园建筑与规划的历史<ArrowUpRight size={14}/></a><a href="https://github.com/IvanZhang22/tsinghua-campus-3d" target="_blank" rel="noreferrer">项目源码与版本记录<ArrowUpRight size={14}/></a></div>{p.stats&&<p className="performance" data-fps={p.stats.fps} data-calls={p.stats.calls} data-triangles={p.stats.triangles}>当前画面：{p.stats.fps} 帧/秒 · {p.stats.calls} 绘制批次</p>}<h3>地形核查清单</h3>{terrainReview.map(t=><p key={t.name}><strong>{t.name}</strong><br/>{t.status}</p>)}<p className="modal-footnote">外部导览 · 地标与住宅示意 · 资料链接见各建筑详情</p></section></div>}
 </div>;
}
