import {useState} from 'react';
import {createPortal} from 'react-dom';
import {Camera,ChevronLeft,ChevronRight,ExternalLink,MapPin,X} from 'lucide-react';
import type {Landmark} from '../types';
export function PlaceEvidence({place}:{place:Landmark}){
 const [index,setIndex]=useState(0),[zoom,setZoom]=useState(false),[failed,setFailed]=useState(false);
 const photos=place.photos??[],photo=photos[index%Math.max(1,photos.length)];
 return <><div className="photo-gallery">{photo&&!failed?<button className="photo-open" onClick={()=>setZoom(true)} aria-label={`放大${place.name}实拍照片`}><img src={photo.src} alt={`${place.name}实拍 · ${photo.author}`} loading="lazy" onError={()=>setFailed(true)}/><span><Camera size={13}/>实拍对照 · 点击放大</span></button>:<div className="photo-pending"><Camera size={28}/><strong>实拍资料待补充</strong><span>尚未找到可明确复用的照片</span></div>}{photos.length>1&&<div className="photo-controls"><button aria-label="上一张照片" onClick={()=>setIndex(i=>(i+photos.length-1)%photos.length)}><ChevronLeft size={16}/></button><span>{index+1} / {photos.length}</span><button aria-label="下一张照片" onClick={()=>setIndex(i=>(i+1)%photos.length)}><ChevronRight size={16}/></button></div>}{photo&&<p className="photo-credit">摄影：{photo.author} · <a href={photo.licenseUrl} target="_blank" rel="noreferrer">{photo.license}</a><a href={photo.source} target="_blank" rel="noreferrer">原图与授权<ExternalLink size={10}/></a></p>}</div>{place.geo&&<section className="geo-evidence"><h3><MapPin size={14}/>地理依据</h3><p className="geo-status">{place.geo.status}</p><p>{place.geo.source}</p><dl><dt>经纬度参考 · WGS84</dt><dd>{place.geo.coordinates[1].toFixed(6)}° N<br/>{place.geo.coordinates[0].toFixed(6)}° E</dd></dl><p className="elevation-pending">{place.geo.elevation}</p><small>资料核对：{place.geo.date} · 坐标不作测量值使用</small></section>}{zoom&&photo&&createPortal(<div className="modal-overlay photo-overlay" onClick={()=>setZoom(false)}><section className="photo-modal" role="dialog" aria-modal="true" aria-label={`${place.name}实拍对照`} onClick={e=>e.stopPropagation()}><button className="icon-button" aria-label="关闭实拍照片" onClick={()=>setZoom(false)}><X size={20}/></button><img src={photo.src} alt={`${place.name}实拍照片`}/><h2>{place.name} · 实拍对照</h2><p>摄影：{photo.author} · {photo.date||'拍摄日期见原图'} · <a href={photo.licenseUrl} target="_blank" rel="noreferrer">{photo.license}</a></p><a href={photo.source} target="_blank" rel="noreferrer">查看原图、拍摄说明与授权<ExternalLink size={13}/></a></section></div>,document.body)}</>;
}
