import { useMemo, useLayoutEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import type { Landmark, Season } from '../types';
import {polygonGeometry} from './geometry';
const unitBox=new THREE.BoxGeometry(1,1,1),unitColumn=new THREE.CylinderGeometry(1,1,1,12),unitSphere=new THREE.SphereGeometry(1,24,12,0,Math.PI*2,0,Math.PI/2);
const palette={brick:'#a76049',stone:'#ede4cf',roof:'#615e59',white:'#f4efe0',glass:'#72969a',dark:'#6a6a62',wood:'#775245'};
const materials=new Map<string,THREE.MeshStandardMaterial>();
function mat(c:string){if(!materials.has(c))materials.set(c,new THREE.MeshStandardMaterial({color:c,roughness:c===palette.glass?.36:.86,metalness:c===palette.glass?.2:0}));return materials.get(c)!;}
const roofGeometry=(()=>{const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute([-.5,0,-.5,.5,0,-.5,0,1,-.5,-.5,0,.5,.5,0,.5,0,1,.5],3));g.setIndex([0,2,1,3,4,5,0,3,5,0,5,2,1,2,5,1,5,4,0,1,4,0,4,3]);g.computeVertexNormals();return g;})();
type BoxProps={p?:[number,number,number];s:[number,number,number];c?:string;r?:number};
function Box({p=[0,0,0],s,c=palette.brick,r=0}:BoxProps){return <mesh geometry={unitBox} material={mat(c)} position={p} scale={s} rotation={[0,r,0]} castShadow receiveShadow dispose={null}/>;}
function Roof({p=[0,0,0],s,c=palette.roof,r=0}:BoxProps){return <mesh geometry={roofGeometry} material={mat(c)} position={p} scale={s} rotation={[0,r,0]} castShadow receiveShadow dispose={null}/>;}
function Column({x,z,h,r=.8,y=0,c=palette.white}:{x:number;z:number;h:number;r?:number;y?:number;c?:string}){return <group><mesh geometry={unitColumn} material={mat(c)} position={[x,y+h/2,z]} scale={[r,h,r]} castShadow dispose={null}/><Box p={[x,y+.3,z]} s={[r*2.7,.7,r*2.7]} c={c}/><Box p={[x,y+h-.2,z]} s={[r*2.5,.65,r*2.5]} c={c}/></group>;}
function Windows({w,h,d,cols=6,rows=3}:{w:number;h:number;d:number;cols?:number;rows?:number}){return <>{Array.from({length:cols*rows},(_,i)=>{const x=(i%cols+.5)*w/cols-w/2,y=(Math.floor(i/cols)+.7)*h/(rows+.5);return <group key={i}><Box p={[x,y,d/2+.12]} s={[Math.min(3.4,w/cols*.45),Math.min(4.8,h/(rows+1)*.6),.25]} c={palette.glass}/><Box p={[x,y-2,d/2+.35]} s={[Math.min(4,w/cols*.55),.4,.65]} c={palette.stone}/></group>;})}</>;}
function Heritage({w,h,d,cols=7}:{w:number;h:number;d:number;cols?:number}){const body=h*.75;return <><Box p={[0,body/2,0]} s={[w,body,d]}/><Box p={[0,1,0]} s={[w+2,2,d+2]} c={palette.stone}/><Box p={[0,body,0]} s={[w+3,1.4,d+3]} c={palette.stone}/><Roof p={[0,body+.7,0]} s={[w+5,h*.23,d+5]}/><Windows w={w*.92} h={body} d={d} cols={cols} rows={Math.max(2,Math.floor(body/7))}/><Box p={[0,4,d/2+.5]} s={[5,8,.6]} c={palette.dark}/></>;}
function Sign({text,w=16,h=4,p}:{text:string;w?:number;h?:number;p:[number,number,number]}){const texture=useMemo(()=>{const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=256;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#f6f2e5';ctx.fillRect(0,0,1024,256);ctx.fillStyle='#323433';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='160px KaiTi, STKaiti, serif';ctx.fillText(text,512,132);const tex=new THREE.CanvasTexture(canvas);tex.colorSpace=THREE.SRGBColorSpace;return tex;},[text]);return <mesh position={p}><planeGeometry args={[w,h]}/><meshStandardMaterial map={texture} roughness={1}/></mesh>;}
function Gate({w,h,d}:{w:number;h:number;d:number}){
 const g=useMemo(()=>{const s=new THREE.Shape();s.moveTo(-w/2,0);s.lineTo(w/2,0);s.lineTo(w/2,h*.75);s.lineTo(-w/2,h*.75);s.closePath();[-w*.3,0,w*.3].forEach((x,i)=>{const r=i===1?w*.115:w*.083,top=i===1?h*.65:h*.5,stem=top-r;const hole=new THREE.Path();hole.moveTo(x-r,0);hole.lineTo(x-r,stem);hole.absarc(x,stem,r,Math.PI,0,true);hole.lineTo(x+r,0);hole.closePath();s.holes.push(hole);});const geometry=new THREE.ExtrudeGeometry(s,{depth:d*.55,bevelEnabled:false});geometry.translate(0,0,-d*.275);return geometry;},[w,h,d]);
 return <><mesh geometry={g} material={mat(palette.white)} castShadow receiveShadow/><Box p={[0,h*.77,0]} s={[w+2,1.2,d*.72]} c={palette.white}/><Box p={[0,h*.83,0]} s={[w+4,.6,d*.88]} c={palette.stone}/><Box p={[0,h*.92,0]} s={[w*.38,h*.17,d*.6]} c={palette.white}/>{[-w/2+.8,-w*.175,w*.175,w/2-.8].map(x=><Column key={x} x={x} z={d*.34} h={h*.76} r={.85}/>)}<Sign text="清华园" w={w*.3} h={h*.17} p={[0,h*.91,d*.31+.05]}/></>;
}
function Dome({w,h,d}:{w:number;h:number;d:number}){const r=w*.24,b=h*.48;return <><Box p={[0,b/2,0]} s={[w*.68,b,d*.65]}/><Box p={[0,1,0]} s={[w*.78,2,d*.76]} c={palette.stone}/><mesh geometry={unitColumn} material={mat(palette.brick)} position={[0,b+3,-d*.08]} scale={[r,6,r]} castShadow dispose={null}/><mesh geometry={unitSphere} material={mat('#6d7973')} position={[0,b+6,-d*.08]} scale={[r,r*.73,r]} castShadow dispose={null}/><Column x={0} z={-d*.08} y={b+6+r*.73} h={2} r={.8} c={palette.stone}/><Box p={[0,b*.65,d*.32]} s={[w*.62,b*.55,d*.2]} c={palette.stone}/>{Array.from({length:4},(_,i)=><Column key={i} x={(i-1.5)*w*.16} z={d*.46} h={b*.82} r={.62} y={1.5}/>)}<Roof p={[0,b*.89,d*.39]} s={[w*.66,h*.12,d*.25]} c={palette.stone}/><Box p={[0,1,d*.48]} s={[w*.73,2.1,d*.2]} c={palette.stone}/><Windows w={w*.7} h={b*.9} d={d*.65} cols={7} rows={2}/></>;}
function Courtyard({w,h,d}:{w:number;h:number;d:number}){return <>{[-1,1].map(k=><group key={k} position={[0,0,k*d*.36]}><Box p={[0,h*.35,0]} s={[w,h*.7,d*.2]} c={palette.wood}/><Roof p={[0,h*.7,0]} s={[w+4,h*.28,d*.25]}/>{Array.from({length:9},(_,i)=><Column key={i} x={(i-4)*w/10} z={d*.12} h={h*.66} r={.42} c={palette.wood}/>)}</group>)}<Box p={[0,h*.3,0]} s={[w*.15,h*.6,d*.64]} c={palette.wood}/><Roof p={[0,h*.6,0]} s={[d*.65,h*.25,w*.22]} r={Math.PI/2}/><Box p={[0,.25,0]} s={[w*.85,.5,d*.8]} c="#ddd0b2"/></>;}
function Pavilion({x=0,z=0,w=15,h=8}:{x?:number;z?:number;w?:number;h?:number}){return <group position={[x,0,z]}><Box p={[0,.45,0]} s={[w+2,.9,w+2]} c={palette.stone}/>{[-1,1].flatMap(a=>[-1,1].map(b=><Column key={`${a}${b}`} x={a*w*.4} z={b*w*.4} h={h*.7} r={.5} c={palette.wood}/>))}<Roof p={[0,h*.7,0]} s={[w+4,h*.3,w+4]}/></group>;}
function Garden({w,d}:{w:number;d:number}){return <><mesh position={[0,1,0]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[w*.2,28]}/><meshStandardMaterial color="#a0b379" roughness={1}/></mesh><Pavilion w={19} h={10}/><Box p={[w*.29,1,0]} s={[w*.38,1,d*.07]} c={palette.stone}/>{Array.from({length:9},(_,i)=><Box key={i} p={[w*.2+i*w*.025,2.5+Math.sin(i/8*Math.PI)*2,0]} s={[2,1,d*.11]} c={palette.white}/>)}<Pavilion x={-w*.28} z={d*.2} w={12} h={8}/></>;}
function Main({w,h,d,year=2025}:{w:number;h:number;d:number;year?:number}){return <>{(year<1990?[-1,1]:[-1,0,1]).map(k=>{const bw=k===0?w*.32:w*.25,bh=k===0?h:h*.65,bd=k===0?d:d*.7;return <group key={k} position={[k*w*.355,0,0]}><Box p={[0,bh/2,0]} s={[bw,bh,bd]} c="#d5b994"/><Box p={[0,bh,0]} s={[bw+3,1.8,bd+3]} c={palette.stone}/><Windows w={bw*.93} h={bh} d={bd} cols={k===0?7:6} rows={Math.floor(bh/7)}/>{k===0&&<><Box p={[0,h*.7,bd/2+1]} s={[18,h*.45,3]} c={palette.stone}/><Box p={[0,h*.58,bd/2+3]} s={[9,h*.36,3]} c={palette.glass}/><Roof p={[0,h+1,0]} s={[bw*.8,4,bd*.8]} c={palette.dark}/></>}</group>;})}{[-1,1].map(k=><Box key={k} p={[k*w*.18,h*.19,0]} s={[w*.15,h*.36,d*.42]} c="#d5b994"/>)}<Box p={[0,.5,d*.7]} s={[w*.98,1,d*.5]} c="#d9d0bb"/></>;}
function Modern({w,h,d,color='#d0c9b8'}:{w:number;h:number;d:number;color?:string}){return <><Box p={[0,h/2,0]} s={[w,h,d]} c={color}/><Box p={[0,h+1,0]} s={[w+2,2,d+2]} c={palette.stone}/><Windows w={w*.95} h={h} d={d} cols={8} rows={Math.max(3,Math.floor(h/6))}/><Box p={[0,h*.4,d/2+.6]} s={[w*.22,h*.7,1.2]} c={palette.glass}/><Box p={[0,1,d/2+4]} s={[w*.38,2,8]} c={palette.stone}/></>;}
function Law({w,h,d}:{w:number;h:number;d:number}){return <><Box p={[0,h/2,0]} s={[w,h,d]} c="#b8a68b"/><Box p={[0,h*.5,d*.505]} s={[w*.96,h*.94,.4]} c={palette.glass}/><Box p={[w*.505,h*.5,0]} s={[.4,h*.94,d*.96]} c={palette.glass}/>{Array.from({length:17},(_,i)=><group key={i}><Box p={[(i-8)*w/18,h*.5,d*.52]} s={[1.8,h*.94,2]} c={i%3===0?'#e6d4b5':'#cdb590'}/><Box p={[w*.52,h*.5,(i-8)*d/18]} s={[2,h*.94,1.8]} c={i%3===0?'#e6d4b5':'#cdb590'}/></group>)}<Box p={[0,h+.5,0]} s={[w+3,1.2,d+3]} c={palette.stone}/><Box p={[0,h+1.5,0]} s={[w*.55,1,d*.55]} c="#758b83"/><Box p={[0,2,d/2+5]} s={[w*.6,4,10]} c={palette.stone}/><Sign text="胡宝星法律图书馆" w={w*.65} h={3.5} p={[0,h*.87,d*.54]}/></>;}
function Technology({w,h,d}:{w:number;h:number;d:number}){return <>{[-1,1].map(k=><group key={k} position={[k*w*.32,0,0]}><Modern w={w*.33} h={h*(k===1?.88:1)} d={d} color="#d1d7d2"/></group>)}<group position={[0,0,-d*.33]}><Modern w={w*.38} h={h*.78} d={d*.3} color="#d7d8ce"/></group><Box p={[0,.3,0]} s={[w*.27,.6,d*.7]} c="#c3cebb"/><Box p={[0,h*.4,d*.35]} s={[w*.35,4,d*.11]} c={palette.stone}/><Sign text="李兆基科技大楼" w={30} h={4} p={[w*.32,h*.79,d/2+.3]}/></>;}
function Dorms({w,h,d}:{w:number;h:number;d:number}){return <>{[-1,1].flatMap(x=>[-1,1].map(z=><group key={`${x}${z}`} position={[x*w*.25,0,z*d*.27]}><Box p={[0,h/2,0]} s={[w*.36,h,d*.34]} c={palette.white}/><Roof p={[0,h,0]} s={[w*.4,3,d*.39]}/><Windows w={w*.34} h={h} d={d*.34} cols={6} rows={4}/><Box p={[w*.16,h*.72,0]} s={[3,h*.55,d*.36]} c={palette.white}/></group>))}</>;}
function Homes({w,d,h}:{w:number;d:number;h:number}){return <>{Array.from({length:8},(_,i)=><group key={i} position={[(i%4-1.5)*w*.24,0,(Math.floor(i/4)-.5)*d*.5]}><Heritage w={w*.18} h={h} d={d*.29} cols={3}/></group>)}</>;}
function FootprintBuilding({l}:{l:Landmark}){
 const [w,h,d]=l.size;
 const classic=['school','science','mechanical','library','gym','guestJia','guestBing','guyu','teach1','teach2'].includes(l.id);
 const color=classic?palette.brick:l.id==='six'?'#b5674f':l.id==='humanities'?'#a68f78':l.id==='museum'?'#c39573':l.id==='mingli'||l.id==='main'?'#d8c5a6':l.category==='dining'?'#c5ab8a':'#d4c8b3';
 const rings=l.footprints??[[[l.position[0]-w/2,l.position[1]-d/2],[l.position[0]+w/2,l.position[1]-d/2],[l.position[0]+w/2,l.position[1]+d/2],[l.position[0]-w/2,l.position[1]+d/2]]];
 return <>{rings.map((ring,k)=>{const points=ring.map(([x,z])=>[x-l.position[0],z-l.position[1]] as [number,number]);const bh=l.id==='main'?[18,40,18,18,18,12][k]??h:l.id==='library'?[17,20,23][k]??h:h*(classic?.78:.96);const body=polygonGeometry(points,bh),roof=polygonGeometry(points,classic?1.4:.8);
 return <group key={k}><mesh geometry={body} material={mat(color)} castShadow receiveShadow/><mesh geometry={roof} material={mat(classic?palette.roof:palette.stone)} position={[0,bh,0]} receiveShadow/>{points.map((a,i)=>{const b=points[(i+1)%points.length],dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz),ry=Math.atan2(-dz,dx);if(len<3)return null;const cols=Math.min(24,Math.floor(len/4.2)),rows=Math.min(8,Math.max(1,Math.floor(bh/4.5)));return <group key={i} position={[(a[0]+b[0])/2,0,(a[1]+b[1])/2]} rotation={[0,ry,0]}><Box p={[0,1,0]} s={[len,1.1,.6]} c={palette.stone}/><Box p={[0,bh-.4,0]} s={[len,.8,.8]} c={palette.stone}/>{Array.from({length:cols*rows},(_,n)=>{const x=((n%cols+.5)/cols-.5)*len,y=(Math.floor(n/cols)+.75)*bh/(rows+.4);return <group key={n}><Box p={[x,y,0]} s={[Math.min(classic?1.7:2.6,len/cols*.6),Math.min(classic?2.7:2.2,bh/(rows+1)*.65),.34]} c={palette.glass}/>{classic&&<Box p={[x,y-1.45,0]} s={[2.1,.22,.6]} c={palette.stone}/>}</group>;})}{l.id==='museum'&&Array.from({length:Math.floor(bh/.9)},(_,n)=><Box key={'fin'+n} p={[0,n*.9+.5,0]} s={[len,.16,.65]} c="#a17d62"/>)}{classic&&len>25&&<Roof p={[0,bh+1,0]} s={[len+1,2.5,Math.min(8,d*.22)]}/>}</group>;})}</group>;
 })}<Box p={[0,1.1,d/2+1.8]} s={[Math.min(12,w*.25),2.2,3.6]} c={palette.stone}/>{['school','mechanical'].includes(l.id)&&<><Sign text={l.name} w={Math.min(10,w*.2)} h={1.4} p={[0,h*.62,d/2+.5]}/>{[-1,1].map(k=><Column key={k} x={k*3.4} z={d/2+.5} h={h*.52} r={.48}/>)}</>}</>;
}
function Track({w,d}:{w:number;d:number}){
 const vertical=d>w,L=Math.max(w,d)*.9,W=Math.min(w,d)*.92,r=W/2,c=Math.max(0,L/2-r);
 const oval=(radius:number)=>{const s=new THREE.Shape();s.moveTo(-c,-radius);s.lineTo(c,-radius);s.absarc(c,0,radius,-Math.PI/2,Math.PI/2,false);s.lineTo(-c,radius);s.absarc(-c,0,radius,Math.PI/2,Math.PI*1.5,false);return s;};
 const track=oval(r);const hole=oval(r*.68);track.holes.push(new THREE.Path(hole.getPoints(48)));
 return <group rotation={[0,vertical?Math.PI/2:0,0]}><mesh rotation={[-Math.PI/2,0,0]} position={[0,.2,0]}><shapeGeometry args={[track,48]}/><meshStandardMaterial color="#ae674c" roughness={1}/></mesh>{Array.from({length:7},(_,i)=>{const rr=r*(.7+i*.043),s=oval(rr);s.holes.push(new THREE.Path(oval(rr-.25).getPoints(48)));return <mesh key={i} rotation={[-Math.PI/2,0,0]} position={[0,.24+i*.001,0]}><shapeGeometry args={[s,48]}/><meshBasicMaterial color="#f0decc"/></mesh>;})}<Box p={[0,.08,0]} s={[Math.max(12,L*.64),.15,W*.51]} c="#6d9b63"/>{[-1,1].map(k=><Box key={k} p={[k*L*.32,.29,0]} s={[.25,.06,W*.51]} c="#f1efdc"/>)}{[-1,1].map(k=><Box key={k} p={[0,.29,k*W*.255]} s={[L*.64,.06,.25]} c="#f1efdc"/>)}<Box p={[0,.29,0]} s={[.3,.06,W*.51]} c="#f1efdc"/><mesh rotation={[-Math.PI/2,0,0]} position={[0,.3,0]}><ringGeometry args={[W*.095,W*.095+.25,40]}/><meshBasicMaterial color="#f1efdc"/></mesh></group>;
}
function Model({l,year}:{l:Landmark;year:number}){const [w,h,d]=l.size;const size={w,h,d};switch(l.model){
 case 'footprint':return <FootprintBuilding l={l}/>;
 case 'field':return <Track w={w} d={d}/>;
 case 'court':return <><Box s={[w,.2,d]} c={l.id==='sandVolley'?'#d9c29d':'#659b90'}/>{[-1,1].map(k=><Box key={k} p={[0,.2,k*d*.43]} s={[w*.9,.07,.3]} c="#ede8d8"/>)}<Box p={[0,.2,0]} s={[.3,.07,d*.86]} c="#ede8d8"/></>;
 case 'marker':return <mesh rotation={[-Math.PI/2,0,0]} position={[0,.3,0]}><ringGeometry args={[5,6,24]}/><meshBasicMaterial color="#946294" transparent opacity={.4}/></mesh>;
 case 'pavilion':return <Pavilion w={9} h={7}/>;
 case 'gate':return <Gate {...size}/>;case 'dome':return <Dome {...size}/>;case 'courtyard':return <Courtyard {...size}/>;
 case 'water':return <><Pavilion x={-w*.34} z={-d*.13} w={14} h={h}/><Box p={[0,.5,-d*.45]} s={[w*.85,1,4]} c={palette.stone}/>{Array.from({length:8},(_,i)=><Column key={i} x={(i-3.5)*w*.1} z={-d*.45} h={h*.6} r={.35} c={palette.wood}/>)}<Roof p={[0,h*.6,-d*.45]} s={[w*.9,h*.27,8]}/></>;
 case 'garden':return <Garden {...size}/>;case 'main':return <Main {...size} year={year}/>;case 'law':return <Law {...size}/>;case 'technology':return <Technology {...size}/>;case 'dorm':return <Dorms {...size}/>;case 'houses':return <Homes {...size}/>;case 'neighborhood':return <Homes {...size}/>;
 case 'observatory':return <><mesh geometry={unitColumn} material={mat(palette.stone)} position={[0,h*.34,0]} scale={[w*.39,h*.68,w*.39]} castShadow dispose={null}/><mesh geometry={unitSphere} material={mat('#7c8986')} position={[0,h*.68,0]} scale={[w*.46,h*.32,w*.46]} castShadow dispose={null}/><Box p={[0,h*.19,d*.39]} s={[3,h*.25,1]} c={palette.dark}/></>;
 case 'humanities':return <><Modern {...size} color="#a6694d"/><mesh geometry={unitColumn} material={mat('#a6694d')} position={[0,h*.55,d*.3]} scale={[w*.2,h*.8,w*.2]} castShadow dispose={null}/>{Array.from({length:7},(_,i)=><Box key={i} p={[0,i*h*.12+3,d*.3]} s={[w*.43,.8,w*.43]} c={palette.stone}/>)}</>;
 case 'museum':return <><Modern {...size} color="#c5aa85"/><Box p={[0,h*.4,d*.5+5]} s={[w*.8,h*.65,11]} c="#b99574"/><Box p={[0,h*.4,d*.5+10.6]} s={[w*.55,h*.44,.8]} c={palette.glass}/></>;
 case 'theater':return <><Modern w={w*.7} h={h} d={d} color="#c5a886"/><Box p={[w*.1,h*.24,d*.4]} s={[w*.95,h*.43,d*.5]} c={palette.stone}/><Box p={[w*.1,h*.25,d*.66]} s={[w*.8,h*.38,.7]} c={palette.glass}/></>;
 case 'six':return <>{[-1,1].map(k=><group key={k} position={[k*w*.31,0,0]}><Modern w={w*.36} h={h} d={d} color="#d9c8ad"/></group>)}<Box p={[0,h*.38,-d*.3]} s={[w*.4,h*.72,d*.28]} c={palette.stone}/></>;
 case 'primary':return <>{Array.from({length:6},(_,i)=>{const a=i/6*Math.PI*2;return <group key={i} position={[Math.cos(a)*w*.3,0,Math.sin(a)*d*.3]}><mesh material={mat('#c2c3ba')} position={[0,h*.4,0]} castShadow><cylinderGeometry args={[w*.14,w*.14,h*.8,6]}/></mesh><mesh material={mat(palette.roof)} position={[0,h*.9,0]} castShadow><coneGeometry args={[w*.17,h*.2,6]}/></mesh></group>;})}<Box p={[0,.3,0]} s={[w*.47,.6,d*.47]} c={palette.stone}/></>;
 case 'mingli':return <><Heritage {...size}/><Box p={[0,h*.37,d*.57]} s={[w*.27,h*.74,d*.15]} c={palette.stone}/><Sign text="明理楼" w={13} h={3.5} p={[0,h*.65,d*.65]}/></>;
 case 'highschool':return <>{[-1,1].map(k=><group key={k} position={[k*w*.27,0,0]}><Modern w={w*.4} h={h} d={d*.75} color="#cbb8a5"/></group>)}<Box p={[0,4,d*.37]} s={[w*.17,8,4]} c={palette.stone}/><Sign text="清华附中" w={18} h={3} p={[0,5,d*.4]}/></>;
 case 'library':return <><Heritage w={w*.68} h={h} d={d*.66}/>{year>=1991&&<group position={[-w*.25,0,-d*.31]}><Modern w={w*.48} h={h*.9} d={d*.5} color="#ba8e70"/></group>}{year>=1931&&<group position={[w*.36,0,0]}><Heritage w={w*.22} h={h*.82} d={d*.85} cols={3}/></group>}</>;
 case 'school':return <><Heritage {...size}/><group position={[0,0,d*.35]}><Heritage w={w*.26} h={h*1.05} d={d*.38} cols={3}/></group><Sign text="清华学堂" w={17} h={3} p={[0,h*.63,d*.545]}/></>;
 default:return <Heritage {...size}/>;
}}
export function LandmarkModel({landmark,season:_,active:__,year=2025}:{landmark:Landmark;season:Season;active:boolean;year?:number}){
 const source=useRef<THREE.Group>(null);const [batch,setBatch]=useState<THREE.Group|null>(null);
 useLayoutEffect(()=>{
  if(!source.current)return;const root=source.current;root.updateWorldMatrix(true,true);
  const inverse=root.matrixWorld.clone().invert();const groups=new Map<string,{material:THREE.Material;geometries:THREE.BufferGeometry[]}>();
  const originals:THREE.Mesh[]=[];
  root.traverse(object=>{if(!(object instanceof THREE.Mesh)||Array.isArray(object.material))return;
   const geometry=object.geometry.clone().applyMatrix4(inverse.clone().multiply(object.matrixWorld));
   const key=object.material.uuid+Object.keys(geometry.attributes).sort().join(',')+Boolean(geometry.index);
   if(!groups.has(key))groups.set(key,{material:object.material,geometries:[]});groups.get(key)!.geometries.push(geometry);originals.push(object);
  });
  const result=new THREE.Group();for(const group of groups.values()){
   const geometry=mergeGeometries(group.geometries);group.geometries.forEach(g=>g.dispose());
   if(geometry){const mesh=new THREE.Mesh(geometry,group.material);mesh.castShadow=true;mesh.receiveShadow=true;result.add(mesh);}
  }
  originals.forEach(mesh=>{mesh.visible=false;});setBatch(result);
  return()=>{originals.forEach(mesh=>{mesh.visible=true;});result.traverse(object=>{if(object instanceof THREE.Mesh)object.geometry.dispose();});};
 },[landmark,year]);
 return <group dispose={null}><group ref={source}><Model l={landmark} year={year}/></group>{batch&&<primitive object={batch}/>}</group>;
}
