import fs from 'node:fs/promises';
const choices={gate:['Thu gate.JPG'],dome:['View of Tsinghua Auditorium in Tsinghua University.jpg'],school:['Former Building of Tsinghua Imperial College.jpg'],observatory:['Tsinghua University Observatory.jpg'],library:['Old library of Tsinghua University.JPG'],humanities:['Library for social science in Tsinghua University.JPG'],museum:['Tsinghua University Art Museum Huang Rulun Building (20240707145554).jpg'],technology:['清華大學李兆基科技大樓.jpg'],mechanical:['清華大學機械工程館冬景.jpg'],law:['清華大學法律圖書館.jpg'],mingli:['School of Law of Tsinghua University.JPG'],theater:['New Tsinghua Auditorium.JPG'],art:['Academy of Arts and Design.jpg'],teach1:['No.1 Teaching Building of Tsinghua University.JPG'],teach2:['No.2 Teaching Building of Tsinghua University.JPG'],teach3:['No.3 Teaching Building of Tsinghua University.JPG'],teach4:['No.4 Teaching Building of Tsinghua University.JPG'],teach5:['第五教學樓.jpg'],six:['No.6 Teaching Building of Tsinghua University.JPG'],dingxiang:['Dingxiangyuan Restaurant of Tsinghua University.JPG'],zijingDining:['Panoramagram of Zijingyuan, Tsinghua University.jpg'],comprehensive:['Gymnasium of Tsinghua University.JPG'],swimming:['Natatorium of Tsinghua University.JPG'],highschool:['Gate of Tsinghua University High School at College Entrance Exam 2021 (20210608163306).jpg']};
const catalog=JSON.parse(await fs.readFile('artifacts/reference/photos-catalog.json','utf8')),result={};
await fs.mkdir('public/photos',{recursive:true});
for(const [id,titles] of Object.entries(choices))for(const title of titles){
 const p=catalog.find(p=>p.title==='File:'+title);if(!p){console.log('Missing',id,title);continue;}
 const dest='public/photos/'+id+'.jpg';try{await fs.access(dest);}catch{try{const r=await fetch(p.remote,{signal:AbortSignal.timeout(40000),headers:{'User-Agent':'TsinghuaCampusExplorer/1.1'}});if(!r.ok)throw Error(String(r.status));await fs.writeFile(dest,new Uint8Array(await r.arrayBuffer()));}catch(e){console.log('Download failed',id,e.message);continue;}}
 result[id]=[{src:'/photos/'+id+'.jpg',title,source:p.source,author:p.author,license:p.license,licenseUrl:p.licenseUrl,date:p.date}];
}
await fs.writeFile('src/data/photos.json',JSON.stringify(result,null,2));console.log('Photos saved',Object.keys(result).length);
